server:
  port: 8083

spring:
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST:localhost}/pos_db
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    enabled:false

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

bank:
  api:
    url:
      orders: http://${BANK_API_HOST:localhost}:8083/api/bank-transfer/orders
      payments: http://${BANK_API_HOST:localhost}:8083/api/bank-transfer/payments

backend:
  api:
    url:
      pos-sales: http://${BACKEND_API_HOST:localhost}:8080/api/pos-sales/save