server:
  port: 8083

spring:
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST:localhost}/pos_db?useSSL=false&useServerPrepStmts=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1234}
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    enabled: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

bank:
  api:
    url: http://${BANK_HOST:localhost}:${BANK_PORT:8083}

# backend:
#   api:
#     url:
#       pos-sales: http://${BACKEND_HOST:localhost}/api/pos-sales/save