server:
  port: 8083

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pos_db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    enabled:false

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

