server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pos_db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    enabled:false

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

